### ISSUE TITLE
polish language is stable for version 1.8

### ISSUE THREAD

**Issue by zstanecic** [RHVoice/packages#16]
Hi,
After some tests in dev and alpha, i can declare polish as stable.
There will be updates of the language packs here and there for windows and android to fix small missprnounciations, but the synthesizer is ready for production use. Expect an e-mail from me with some questions, too.

**Comment by Olga-Yakovleva** [comment]
RHVoice 1.8.0 is currently moving through a [staged rollout](https://support.google.com/googleplay/android-developer/answer/6346149?hl=en). I'm expecting to be watching and expanding the rollout over the next couple of days. This is a final check to make sure that this technically major update doesn't break things for users. When I finish this process by making it available to 100% of users, I will merge the Polish voices to the stable package directory.

**Comment by Olga-Yakovleva** [comment]
The Polish voices are now available to anyone in the Android app.
