### ISSUE TITLE
macedonian is stable

### ISSUE THREAD

**Issue by zstanecic** [RHVoice/packages#44]
Ni,
You can merge macedonian from alpha to stable.
The language works correctly with all rules.
I have also built the packages for Suze, in their new respective versions for Sapi.
After the update for android, i will update the release page on github and send you links.

**Comment by Olga-Yakovleva** [comment]
It's now in stable.

**Comment by zstanecic** [comment]
Ok.

Regarding Suze, please check your inbox, and update the site please.

Best,

Zvonimir
