### ISSUE TITLE
explanation for the latest pull requests

### ISSUE THREAD

**Issue by zstanecic** [RHVoice/packages#60]
Language package 1.15 is ready for wider deployment: 
Voices Magda, Cezary, Natan and michal are for the 1.12 core.

**Comment by Olga-Yakovleva** [comment]
The language is published everywhere, the voices are in alpha.

**Comment by zstanecic** [comment]
Hi,

As i have tested the voices in runtime over the weekend, I declare the stability.

These are ready for release.

**Comment by zstanecic** [comment]
Okay.
