### ISSUE TITLE
natural voices

### ISSUE THREAD

**Issue by KiaraGrouwstra** [RHVoice/packages#65]
hi there,
it would be nice if it were possible to add voices closer to the academic state of the art.
one such an existing model would be [tortoise-tts](https://github.com/neonbjb/tortoise-tts/).

**Comment by zstanecic** [comment]
Hi,

It is not so good to be implemented.

Thanks.

 

From: Kiara Grouwstra ***@***.***> 
Sent: Sunday, April 23, 2023 11:33 AM
To: RHVoice/packages ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [RHVoice/packages] natural voices (Issue #65)

 

hi there,
it would be nice if it were possible to add voices closer to the academic state of the art.
one such an existing model would be tortoise-tts <https://github.com/neonbjb/tortoise-tts/> .

**Comment by Olga-Yakovleva** [comment]
We would like to have natural voices, but our priority is responsiveness, as needed by screen

**Comment by Olga-Yakovleva** [comment]
Appologies, a wrong key press. Continuing my comment, we need performance and responsiveness for screen readers, especially on mobile devices.
