### ISSUE TITLE
polish voice update

### ISSUE THREAD

**Issue by zstanecic** [RHVoice/packages#9]
Hi, i am just reminging about the voice update.

**Comment by Olga-Yakovleva** [comment]
Yes, I remember. I'll get to them as soon as I can. I need to do 
somethings just now.

**Comment by zstanecic** [comment]
What exactly? Are there some improvements on the way?

**Comment by Olga-Yakovleva** [comment]
Well, I guess it may surprise some people, but there may be things I 
need to deal with which are not related to RHVoice.

**Comment by zstanecic** [comment]
this was not closed automatically, so closing...
